behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 50
      buffer_size: 5000
      learning_rate: 2e-3
      beta: 1e-3
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 100
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: .5
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 2000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
